### ISSUE TITLE
Can you help me, I can't run the program

### ISSUE THREAD

**Issue by Jason12345** [Cr0mb/BreadCracker#5]
Traceback (most recent call last):
  File "/workspaces/codespaces-blank/BreadCracker/BreadCracker.py", line 170, in <module>
    curses.wrapper(main)
  File "/home/codespace/.python/current/lib/python3.12/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/codespaces-blank/BreadCracker/BreadCracker.py", line 159, in main
    stdscr.addstr(6, 0, wallet_info, curses.color_pair(1))
_curses.error: addwstr() returned ERR

**Comment by Elsiehwoods** [comment]
@Jason12345 It looks like you're running into a curses error in your Python script. The `_curses.error: addwstr() returned ERR` usually happens when trying to write outside the window boundaries or if the string is too long for the line.
